#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use ShakeTheNations\DependencyInjection\Application;
use ShakeTheNations\Console\ConsoleApplication;

$app = new Application();
$console = new ConsoleApplication($app);
$console->run();
